### PR TITLE
Add an imports resolver func

### LINKED ISSUE #62: Custom import resolution
First, thanks for this library, it works great.

I'm the lead maintainer of Hugo (https://github.com/gohugoio/hugo) and I'm about to add SASS support to Hugo via go-libsass/libsass. I hope we can switch out that with a native Go library eventually, but after thinking hard, I concluded that I/we really need this now.

I have a very convincing demo of this working in Hugo (https://twitter.com/GoHugoIO/status/1007361748201037824) -- but I have one problem that I would really like to solve to get this where I want it.

In Hugo we have a layered and virtual filesystem with a well defined order (project, themes). Setting `IncludePaths` with a list of these directories works mostly as I want, but LibSass seems to always prefer the local relative import if present.

I know which import should be picked, so if I could hook in a "import resolver" func given the file path and import path, I could provide the correct import filename.

Looking at the LibSass API, it looks like this should be possible, but I would appreciate any help/hint in this area.

### PR DESCRIPTION
**Pull request by bep**
There are some potentials in improving the API in this areea; this PR focuses on making my use case work and not breaking people using the import slice.

Fixes #62

### CODE REVIEW

**Comment by drewwells** [comment]
changes look good, breaks backwards compat. I guess it's time for a new major release

**Comment by bep** [comment]
Not sure how this patch is breaking anything?

**Comment by bep** [comment]
Ah, ok the BindImporter func -- I guess we could add a variant of that if needed.

**Comment by drewwells** [comment]
I'm going to change something in this implementation.

The resolver will move into imports struct replacing the hardcoded bytes. I believe that will cover your usecase. Importers are intended to be shared in a compiler, so having a single resolver will not give the compiler much flexibility.

**Pull request merged**
